### ISSUE TITLE
Problem with using fields of type 'array' in model

### ISSUE THREAD

**Issue by skondakov** [atk4/audit#21]
When I use fields of type 'array' like:

`$this->addField('template_vars', ['type' => 'array', 'serialize' => 'json']);`

I get an error like this, when I have an audit logging enabled for this model:

https://www.screencast.com/t/z9dLvrqmfC

**Comment by DarkSide666** [comment]
@skondakov please check. Maybe #22 also fix this issue you had.

**Comment by DarkSide666** [comment]
Should be fixed by https://github.com/atk4/audit/commit/a656dd9a9d5c8582c29b404c19f4ece8e3f9cc72

**Comment by romaninsh** [comment]
reopen if issue is still there.
